/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TicketStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'waitingForParts' : IDL.Null,
  'inProgress' : IDL.Null,
  'ready' : IDL.Null,
});
export const StatusLog = IDL.Record({
  'status' : TicketStatus,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});
export const RepairTicket = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'contactInfo' : IDL.Text,
  'issueDescription' : IDL.Text,
  'technicianNotes' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'statusHistory' : IDL.Vec(StatusLog),
  'priceEstimate' : IDL.Opt(IDL.Float64),
  'deviceBrand' : IDL.Text,
  'currentStatus' : TicketStatus,
  'deviceModel' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTicket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllTickets' : IDL.Func([], [IDL.Vec(RepairTicket)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyTickets' : IDL.Func([], [IDL.Vec(RepairTicket)], ['query']),
  'getTicketDetails' : IDL.Func([IDL.Nat], [RepairTicket], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateTicketStatus' : IDL.Func(
      [IDL.Nat, TicketStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Float64)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TicketStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'waitingForParts' : IDL.Null,
    'inProgress' : IDL.Null,
    'ready' : IDL.Null,
  });
  const StatusLog = IDL.Record({
    'status' : TicketStatus,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  const RepairTicket = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'contactInfo' : IDL.Text,
    'issueDescription' : IDL.Text,
    'technicianNotes' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'statusHistory' : IDL.Vec(StatusLog),
    'priceEstimate' : IDL.Opt(IDL.Float64),
    'deviceBrand' : IDL.Text,
    'currentStatus' : TicketStatus,
    'deviceModel' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTicket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllTickets' : IDL.Func([], [IDL.Vec(RepairTicket)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyTickets' : IDL.Func([], [IDL.Vec(RepairTicket)], ['query']),
    'getTicketDetails' : IDL.Func([IDL.Nat], [RepairTicket], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateTicketStatus' : IDL.Func(
        [IDL.Nat, TicketStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Float64)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };