/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RepairTicket {
  'id' : bigint,
  'customerName' : string,
  'contactInfo' : string,
  'issueDescription' : string,
  'technicianNotes' : [] | [string],
  'createdAt' : Time,
  'createdBy' : Principal,
  'statusHistory' : Array<StatusLog>,
  'priceEstimate' : [] | [number],
  'deviceBrand' : string,
  'currentStatus' : TicketStatus,
  'deviceModel' : string,
}
export interface StatusLog {
  'status' : TicketStatus,
  'notes' : [] | [string],
  'timestamp' : Time,
}
export type TicketStatus = { 'new' : null } |
  { 'closed' : null } |
  { 'waitingForParts' : null } |
  { 'inProgress' : null } |
  { 'ready' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTicket' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'getAllTickets' : ActorMethod<[], Array<RepairTicket>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyTickets' : ActorMethod<[], Array<RepairTicket>>,
  'getTicketDetails' : ActorMethod<[bigint], RepairTicket>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateTicketStatus' : ActorMethod<
    [bigint, TicketStatus, [] | [string], [] | [number]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];